"""
Text Embedding Data Structures.

This module defines an ontology model for text embeddings.
It exists for datasets that expose learned language vectors instead of raw text, or
alongside it.
"""

from mosaicolabs import MosaicoField, MosaicoType, Serializable


class TextEmbedding(Serializable):
    """Store a text embedding as an ordered floating-point vector.

    The model exists so packs can preserve semantic features generated by an external
    text encoder without collapsing them back into plain strings or tying the pack to
    a specific embedding provider API.

    Attributes:
        values: Ordered embedding vector produced by the source encoder.
    """

    __ontology_tag__ = "text_embedding"

    values: MosaicoType.list_(MosaicoType.float32) = MosaicoField(
        description="Values of the text embedding."
    )
